FROM node:14-alpine3.10

ENV TZ=Africa/Kampala

LABEL version="1.0"
LABEL descriptionn="Development image for Server"

# we include procps and telnet so you can use these with shell.sh prompt
RUN npm install yarn

# set up and copy files to /home/app
ENV HOME=/usr/app
WORKDIR /home/app
COPY . /home/app

# install our NodeJS packages (from package.json)
RUN yarn 

# we run a script to stat the server; the array syntax makes it so ^C will work as we want
CMD  ["yarn", "server"]
